version: '3.3'

services:
  traefik:
    image: traefik:1.7.5
    restart: always
    command:
      - --api
      - --docker
      - --logLevel=INFO
    networks:
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
    env_file: 
      - /home/jphuc96/docker_data/traefik/traefik.env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      # - "traefik.frontend.rule=Host:traefik.sudojoss.com"
      - "traefik.frontend.rule=Host:www.sudojoss.com; PathPrefixStrip:/traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=sudojoss.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jphuc96/docker_data/traefik/traefik.toml:/traefik.toml
      - /home/jphuc96/docker_data/traefik/rules.toml:/rules.toml
      - /home/jphuc96/docker_data/traefik/acme.json:/acme.json
      - /home/jphuc96/docker_data/traefik/files:/files/
networks:
  traefik_proxy:
    external: true
